name: Java CI with Maven and jpackage (Windows)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: 'maven'

    - name: Extract project version
      id: get_version
      run: echo "project_version=$(mvn -q -DforceStdout help:evaluate -Dexpression=project.version)" >> $env:GITHUB_ENV
      shell: pwsh

    - name: Build with Maven (jlink phase)
      run: mvn -B clean install javafx:jlink --file pom.xml

    - name: Run jpackage
      shell: pwsh
      run: jpackage --type "app-image" --name "Hashana" --dest "target/installer" --runtime-image "target/hashana-runtime" --module me.yurinero.hashana/me.yurinero.hashana.Hashana --app-version ${{ env.project_version }}

    - name: Archive application image
      uses: actions/upload-artifact@v4
      with:
        name: Hashana-Windows-AppImage-${{ env.project_version }}
        path: target/installer/Hashana/
        if-no-files-found: error
