name: Simple Trigger Test

on:
  push:
    branches: [ master ]

jobs:
  test_job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo a message
        run: echo "Simple test workflow triggered successfully!"
